<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NDI-LAP-591" ignored="0" name="Default test" tests="4" failures="0" timestamp="26 Apr 2019 06:23:39 GMT" time="39.396" errors="0">
  <testcase name="@AfterMethod returntoHomePage" time="0.0" classname="sheinTest.BaseTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at sheinTest.BaseTest.returntoHomePage(BaseTest.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @AfterMethod returntoHomePage -->
  <testcase name="@AfterMethod returntoHomePage" time="0.0" classname="sheinTest.BaseTest">
    <skipped/>
  </testcase> <!-- @AfterMethod returntoHomePage -->
  <testcase name="@AfterMethod returntoHomePage" time="0.0" classname="sheinTest.BaseTest">
    <skipped/>
  </testcase> <!-- @AfterMethod returntoHomePage -->
  <testcase name="@AfterMethod returntoHomePage" time="0.0" classname="sheinTest.BaseTest">
    <skipped/>
  </testcase> <!-- @AfterMethod returntoHomePage -->
  <testcase name="@AfterClass afterClass" time="0.0" classname="sheinTest.BaseTest">
    <skipped/>
  </testcase> <!-- @AfterClass afterClass -->
  <testcase name="verifycompanylogo" time="0.042" classname="sheinTest.HomeTest"/>
  <testcase name="verifyloginpage" time="0.0" classname="sheinTest.HomeTest">
    <skipped/>
  </testcase> <!-- verifyloginpage -->
  <testcase name="verifyloinbutton" time="0.0" classname="sheinTest.HomeTest">
    <skipped/>
  </testcase> <!-- verifyloinbutton -->
  <testcase name="verifymenuoption" time="0.0" classname="sheinTest.HomeTest">
    <skipped/>
  </testcase> <!-- verifymenuoption -->
</testsuite> <!-- Default test -->
